### ISSUE TITLE
maya import error

### ISSUE THREAD

**Issue by qqba** [wgergely/bookmarks#52]
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: invalid syntax //
# Warning: Failed to run file: C:/Users/Administrator/Documents/maya/plug-ins/Bookmarks.py, at line 1, in "sys"
# Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: invalid syntax #
# Warning: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Failed to run file: C:/Users/Administrator/Documents/maya/plug-ins/Bookmarks.py #
# Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317:  (Bookmarks) #
loaded error
Maya2020.4

**Comment by wgergely** [comment]
Hi there,

I can't tell exactly why this occurs but my guess is that you're trying to run Bookmarks from a  **Python 2** Maya environment?
Bookmarks only supports **Python 3**, sorry. I can't remember if Maya 2020 came with Python 3 enabled but the more recent versions (2022+) definitely do.

**Comment by qqba** [comment]
thanks for the reply
maya2022.4 error
// Loading Bookmarks... // 
# Error: ModuleNotFoundError: file D:\software\Bookmarks\shared\psutil\_pswindows.py line 35: No module named 'psutil._psutil_windows' # 
maya2023.2 can run normally

**Comment by qqba** [comment]
Save the file, the file size is 0kb

**Comment by qqba** [comment]
![Snipaste_2023-01-14_12-53-22](https://user-images.githubusercontent.com/88070163/212455778-21049242-d563-4473-8704-aaf946b0a256.png)

**Comment by wgergely** [comment]
Great - glad to hear it runs using Maya 2023.
Admittedly, this project is lacking a good testing environment setup so I have been working against Maya 2023 only. I don't immediately see why psutils would fail in 2022 since I assumed they both 2022 and 2023 run the same Python environment.

What I'll do, is try to get Maya 2022 set up in a sandbox and see if I'm doing something wrong on my side and I will also look into clarifying the Python 2/3 situation - perhaps by adding a version check to the Maya plugin.

**Comment by wgergely** [comment]
> ![Snipaste_2023-01-14_12-53-22](https://user-images.githubusercontent.com/88070163/212455778-21049242-d563-4473-8704-aaf946b0a256.png)

 Would you be so kind as to open a new issue for this so we can discuss separately? Thank you very much🙏

**Comment by qqba** [comment]
thanks for the reply 
no problem

> > ![Snipaste_2023-01-14_12-53-22](https://user-images.githubusercontent.com/88070163/212455778-21049242-d563-4473-8704-aaf946b0a256.png)
> 
> Would you be so kind as to open a new issue for this so we can discuss separately? Thank you very much🙏

thanks for the reply 
no problem
