### ISSUE TITLE
maya save file problem

### ISSUE THREAD

**Issue by qqba** [wgergely/bookmarks#53]
![Snipaste_2023-01-14_12-53-22](https://user-images.githubusercontent.com/88070163/212467180-bfeeb204-927a-4454-b825-f5170dbc90fb.png)

**Comment by wgergely** [comment]
This might very well be the "expected" behaviour if you made these files using "Add file..." dialog (accessable from the Files tab using the context menu):

![image](https://user-images.githubusercontent.com/11316825/212470583-1b697a2c-d498-46fb-a320-d6c57401d62b.png)
_(this option is meant to create template files to use as naming references in DCC - so it will create an empty file that can be later overriden when saving a scene)._



However, the Maya plugin does come with it's own scene saver. To access it, press and hold **"shift"** before right-clicking on the file tab window:

![image](https://user-images.githubusercontent.com/11316825/212470842-2f0b7ed6-e50f-4222-8223-fa0ffb777c51.png)
_Notice it says "Save Scene..." when using ```shift+right-click```: in theory this should save the current Maya scene to permanent storage._

(The same saver is accessible from the Bookmarks tool button):
![image](https://user-images.githubusercontent.com/11316825/212470974-91278e74-bb23-4f76-8629-2a1e6100e884.png)

---

Let me know if you still having issues saving the scene after this!

**Comment by wgergely** [comment]
I realise the user documentation is non-existent at the moment (sorry!). When time permits, I'll make sure basic usage is explained for reference 🤦‍♂️

**Comment by qqba** [comment]
> 我意识到用户文档目前不存在（对不起！如果时间允许，我将确保解释基本用法以供参考🤦‍♂️

According to the method you provided
can solve the current problem
thanks

**Comment by wgergely** [comment]
Great, thanks for the feedback.
