### ISSUE TITLE
An error is reported when starting the plugin

### ISSUE THREAD

**Issue by g2mXagent** [wgergely/bookmarks#7]
1. download Bookmarks_setup_0.3.7.exe
2. install (all default settings)
3. start Maya
4. start mBookmarks.py
5. got this:
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: EnvironmentError: file E:/Users/g2m.agent/Documents/maya/plug-ins/mBookmarks.py line 44: Is Bookmarks installed?
(Environment variable `BOOKMARKS_ROOT` is not set.) //
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: EnvironmentError: file E:/Users/g2m.agent/Documents/maya/plug-ins/mBookmarks.py line 44: Is Bookmarks installed?
(Environment variable `BOOKMARKS_ROOT` is not set.) //
// Warning: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Failed to call script initialize function //
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317:  (mBookmarks) //
----------------------------------------------------
Windows10, Maya 2020.4

**Comment by wgergely** [comment]
Thanks for flagging this up. I'm in the process of a major overhaul of the code-base and I haven't yet had the chance to touch the Maya module. There're will soon be an update to the binaries but I'll have to make sure the plugin is tested against the latest Maya release before I get to that point.

FYI - The Windows installer should set the `BOOKMARKS_ROOT` environment variable and point it at the install directory. If I remember well, the Maya module uses the value of BOOKMARKS_ROOT to locate the python modules it has to load to run Bookmarks.
Are you loading Maya with custom environment values?

**Comment by g2mXagent** [comment]
The problem is solved. I need to restart the computer.
